
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `counts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model counts
 * 
 */
export type countsModel = runtime.Types.Result.DefaultSelection<Prisma.$countsPayload>

export type AggregateCounts = {
  _count: CountsCountAggregateOutputType | null
  _min: CountsMinAggregateOutputType | null
  _max: CountsMaxAggregateOutputType | null
}

export type CountsMinAggregateOutputType = {
  id: string | null
  id_project: string | null
  logged_on: Date | null
}

export type CountsMaxAggregateOutputType = {
  id: string | null
  id_project: string | null
  logged_on: Date | null
}

export type CountsCountAggregateOutputType = {
  id: number
  id_project: number
  logged_on: number
  _all: number
}


export type CountsMinAggregateInputType = {
  id?: true
  id_project?: true
  logged_on?: true
}

export type CountsMaxAggregateInputType = {
  id?: true
  id_project?: true
  logged_on?: true
}

export type CountsCountAggregateInputType = {
  id?: true
  id_project?: true
  logged_on?: true
  _all?: true
}

export type CountsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which counts to aggregate.
   */
  where?: Prisma.countsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of counts to fetch.
   */
  orderBy?: Prisma.countsOrderByWithRelationInput | Prisma.countsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.countsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` counts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` counts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned counts
  **/
  _count?: true | CountsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CountsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CountsMaxAggregateInputType
}

export type GetCountsAggregateType<T extends CountsAggregateArgs> = {
      [P in keyof T & keyof AggregateCounts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCounts[P]>
    : Prisma.GetScalarType<T[P], AggregateCounts[P]>
}




export type countsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.countsWhereInput
  orderBy?: Prisma.countsOrderByWithAggregationInput | Prisma.countsOrderByWithAggregationInput[]
  by: Prisma.CountsScalarFieldEnum[] | Prisma.CountsScalarFieldEnum
  having?: Prisma.countsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CountsCountAggregateInputType | true
  _min?: CountsMinAggregateInputType
  _max?: CountsMaxAggregateInputType
}

export type CountsGroupByOutputType = {
  id: string
  id_project: string
  logged_on: Date | null
  _count: CountsCountAggregateOutputType | null
  _min: CountsMinAggregateOutputType | null
  _max: CountsMaxAggregateOutputType | null
}

export type GetCountsGroupByPayload<T extends countsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CountsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CountsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CountsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CountsGroupByOutputType[P]>
      }
    >
  >



export type countsWhereInput = {
  AND?: Prisma.countsWhereInput | Prisma.countsWhereInput[]
  OR?: Prisma.countsWhereInput[]
  NOT?: Prisma.countsWhereInput | Prisma.countsWhereInput[]
  id?: Prisma.UuidFilter<"counts"> | string
  id_project?: Prisma.UuidFilter<"counts"> | string
  logged_on?: Prisma.DateTimeNullableFilter<"counts"> | Date | string | null
  projects?: Prisma.XOR<Prisma.ProjectsScalarRelationFilter, Prisma.projectsWhereInput>
}

export type countsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  id_project?: Prisma.SortOrder
  logged_on?: Prisma.SortOrderInput | Prisma.SortOrder
  projects?: Prisma.projectsOrderByWithRelationInput
}

export type countsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.countsWhereInput | Prisma.countsWhereInput[]
  OR?: Prisma.countsWhereInput[]
  NOT?: Prisma.countsWhereInput | Prisma.countsWhereInput[]
  id_project?: Prisma.UuidFilter<"counts"> | string
  logged_on?: Prisma.DateTimeNullableFilter<"counts"> | Date | string | null
  projects?: Prisma.XOR<Prisma.ProjectsScalarRelationFilter, Prisma.projectsWhereInput>
}, "id">

export type countsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  id_project?: Prisma.SortOrder
  logged_on?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.countsCountOrderByAggregateInput
  _max?: Prisma.countsMaxOrderByAggregateInput
  _min?: Prisma.countsMinOrderByAggregateInput
}

export type countsScalarWhereWithAggregatesInput = {
  AND?: Prisma.countsScalarWhereWithAggregatesInput | Prisma.countsScalarWhereWithAggregatesInput[]
  OR?: Prisma.countsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.countsScalarWhereWithAggregatesInput | Prisma.countsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"counts"> | string
  id_project?: Prisma.UuidWithAggregatesFilter<"counts"> | string
  logged_on?: Prisma.DateTimeNullableWithAggregatesFilter<"counts"> | Date | string | null
}

export type countsCreateInput = {
  id?: string
  logged_on?: Date | string | null
  projects: Prisma.projectsCreateNestedOneWithoutCountsInput
}

export type countsUncheckedCreateInput = {
  id?: string
  id_project: string
  logged_on?: Date | string | null
}

export type countsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  projects?: Prisma.projectsUpdateOneRequiredWithoutCountsNestedInput
}

export type countsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  id_project?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type countsCreateManyInput = {
  id?: string
  id_project: string
  logged_on?: Date | string | null
}

export type countsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type countsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  id_project?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type countsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_project?: Prisma.SortOrder
  logged_on?: Prisma.SortOrder
}

export type countsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_project?: Prisma.SortOrder
  logged_on?: Prisma.SortOrder
}

export type countsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  id_project?: Prisma.SortOrder
  logged_on?: Prisma.SortOrder
}

export type CountsListRelationFilter = {
  every?: Prisma.countsWhereInput
  some?: Prisma.countsWhereInput
  none?: Prisma.countsWhereInput
}

export type countsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type countsCreateNestedManyWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput> | Prisma.countsCreateWithoutProjectsInput[] | Prisma.countsUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.countsCreateOrConnectWithoutProjectsInput | Prisma.countsCreateOrConnectWithoutProjectsInput[]
  createMany?: Prisma.countsCreateManyProjectsInputEnvelope
  connect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
}

export type countsUncheckedCreateNestedManyWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput> | Prisma.countsCreateWithoutProjectsInput[] | Prisma.countsUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.countsCreateOrConnectWithoutProjectsInput | Prisma.countsCreateOrConnectWithoutProjectsInput[]
  createMany?: Prisma.countsCreateManyProjectsInputEnvelope
  connect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
}

export type countsUpdateManyWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput> | Prisma.countsCreateWithoutProjectsInput[] | Prisma.countsUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.countsCreateOrConnectWithoutProjectsInput | Prisma.countsCreateOrConnectWithoutProjectsInput[]
  upsert?: Prisma.countsUpsertWithWhereUniqueWithoutProjectsInput | Prisma.countsUpsertWithWhereUniqueWithoutProjectsInput[]
  createMany?: Prisma.countsCreateManyProjectsInputEnvelope
  set?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  disconnect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  delete?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  connect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  update?: Prisma.countsUpdateWithWhereUniqueWithoutProjectsInput | Prisma.countsUpdateWithWhereUniqueWithoutProjectsInput[]
  updateMany?: Prisma.countsUpdateManyWithWhereWithoutProjectsInput | Prisma.countsUpdateManyWithWhereWithoutProjectsInput[]
  deleteMany?: Prisma.countsScalarWhereInput | Prisma.countsScalarWhereInput[]
}

export type countsUncheckedUpdateManyWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput> | Prisma.countsCreateWithoutProjectsInput[] | Prisma.countsUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.countsCreateOrConnectWithoutProjectsInput | Prisma.countsCreateOrConnectWithoutProjectsInput[]
  upsert?: Prisma.countsUpsertWithWhereUniqueWithoutProjectsInput | Prisma.countsUpsertWithWhereUniqueWithoutProjectsInput[]
  createMany?: Prisma.countsCreateManyProjectsInputEnvelope
  set?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  disconnect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  delete?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  connect?: Prisma.countsWhereUniqueInput | Prisma.countsWhereUniqueInput[]
  update?: Prisma.countsUpdateWithWhereUniqueWithoutProjectsInput | Prisma.countsUpdateWithWhereUniqueWithoutProjectsInput[]
  updateMany?: Prisma.countsUpdateManyWithWhereWithoutProjectsInput | Prisma.countsUpdateManyWithWhereWithoutProjectsInput[]
  deleteMany?: Prisma.countsScalarWhereInput | Prisma.countsScalarWhereInput[]
}

export type countsCreateWithoutProjectsInput = {
  id?: string
  logged_on?: Date | string | null
}

export type countsUncheckedCreateWithoutProjectsInput = {
  id?: string
  logged_on?: Date | string | null
}

export type countsCreateOrConnectWithoutProjectsInput = {
  where: Prisma.countsWhereUniqueInput
  create: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput>
}

export type countsCreateManyProjectsInputEnvelope = {
  data: Prisma.countsCreateManyProjectsInput | Prisma.countsCreateManyProjectsInput[]
  skipDuplicates?: boolean
}

export type countsUpsertWithWhereUniqueWithoutProjectsInput = {
  where: Prisma.countsWhereUniqueInput
  update: Prisma.XOR<Prisma.countsUpdateWithoutProjectsInput, Prisma.countsUncheckedUpdateWithoutProjectsInput>
  create: Prisma.XOR<Prisma.countsCreateWithoutProjectsInput, Prisma.countsUncheckedCreateWithoutProjectsInput>
}

export type countsUpdateWithWhereUniqueWithoutProjectsInput = {
  where: Prisma.countsWhereUniqueInput
  data: Prisma.XOR<Prisma.countsUpdateWithoutProjectsInput, Prisma.countsUncheckedUpdateWithoutProjectsInput>
}

export type countsUpdateManyWithWhereWithoutProjectsInput = {
  where: Prisma.countsScalarWhereInput
  data: Prisma.XOR<Prisma.countsUpdateManyMutationInput, Prisma.countsUncheckedUpdateManyWithoutProjectsInput>
}

export type countsScalarWhereInput = {
  AND?: Prisma.countsScalarWhereInput | Prisma.countsScalarWhereInput[]
  OR?: Prisma.countsScalarWhereInput[]
  NOT?: Prisma.countsScalarWhereInput | Prisma.countsScalarWhereInput[]
  id?: Prisma.UuidFilter<"counts"> | string
  id_project?: Prisma.UuidFilter<"counts"> | string
  logged_on?: Prisma.DateTimeNullableFilter<"counts"> | Date | string | null
}

export type countsCreateManyProjectsInput = {
  id?: string
  logged_on?: Date | string | null
}

export type countsUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type countsUncheckedUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type countsUncheckedUpdateManyWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logged_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type countsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_project?: boolean
  logged_on?: boolean
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["counts"]>

export type countsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_project?: boolean
  logged_on?: boolean
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["counts"]>

export type countsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  id_project?: boolean
  logged_on?: boolean
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["counts"]>

export type countsSelectScalar = {
  id?: boolean
  id_project?: boolean
  logged_on?: boolean
}

export type countsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "id_project" | "logged_on", ExtArgs["result"]["counts"]>
export type countsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}
export type countsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}
export type countsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | Prisma.projectsDefaultArgs<ExtArgs>
}

export type $countsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "counts"
  objects: {
    projects: Prisma.$projectsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    id_project: string
    logged_on: Date | null
  }, ExtArgs["result"]["counts"]>
  composites: {}
}

export type countsGetPayload<S extends boolean | null | undefined | countsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$countsPayload, S>

export type countsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<countsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CountsCountAggregateInputType | true
  }

export interface countsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['counts'], meta: { name: 'counts' } }
  /**
   * Find zero or one Counts that matches the filter.
   * @param {countsFindUniqueArgs} args - Arguments to find a Counts
   * @example
   * // Get one Counts
   * const counts = await prisma.counts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends countsFindUniqueArgs>(args: Prisma.SelectSubset<T, countsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Counts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {countsFindUniqueOrThrowArgs} args - Arguments to find a Counts
   * @example
   * // Get one Counts
   * const counts = await prisma.counts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends countsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, countsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Counts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsFindFirstArgs} args - Arguments to find a Counts
   * @example
   * // Get one Counts
   * const counts = await prisma.counts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends countsFindFirstArgs>(args?: Prisma.SelectSubset<T, countsFindFirstArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Counts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsFindFirstOrThrowArgs} args - Arguments to find a Counts
   * @example
   * // Get one Counts
   * const counts = await prisma.counts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends countsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, countsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Counts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Counts
   * const counts = await prisma.counts.findMany()
   * 
   * // Get first 10 Counts
   * const counts = await prisma.counts.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const countsWithIdOnly = await prisma.counts.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends countsFindManyArgs>(args?: Prisma.SelectSubset<T, countsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Counts.
   * @param {countsCreateArgs} args - Arguments to create a Counts.
   * @example
   * // Create one Counts
   * const Counts = await prisma.counts.create({
   *   data: {
   *     // ... data to create a Counts
   *   }
   * })
   * 
   */
  create<T extends countsCreateArgs>(args: Prisma.SelectSubset<T, countsCreateArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Counts.
   * @param {countsCreateManyArgs} args - Arguments to create many Counts.
   * @example
   * // Create many Counts
   * const counts = await prisma.counts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends countsCreateManyArgs>(args?: Prisma.SelectSubset<T, countsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Counts and returns the data saved in the database.
   * @param {countsCreateManyAndReturnArgs} args - Arguments to create many Counts.
   * @example
   * // Create many Counts
   * const counts = await prisma.counts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Counts and only return the `id`
   * const countsWithIdOnly = await prisma.counts.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends countsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, countsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Counts.
   * @param {countsDeleteArgs} args - Arguments to delete one Counts.
   * @example
   * // Delete one Counts
   * const Counts = await prisma.counts.delete({
   *   where: {
   *     // ... filter to delete one Counts
   *   }
   * })
   * 
   */
  delete<T extends countsDeleteArgs>(args: Prisma.SelectSubset<T, countsDeleteArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Counts.
   * @param {countsUpdateArgs} args - Arguments to update one Counts.
   * @example
   * // Update one Counts
   * const counts = await prisma.counts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends countsUpdateArgs>(args: Prisma.SelectSubset<T, countsUpdateArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Counts.
   * @param {countsDeleteManyArgs} args - Arguments to filter Counts to delete.
   * @example
   * // Delete a few Counts
   * const { count } = await prisma.counts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends countsDeleteManyArgs>(args?: Prisma.SelectSubset<T, countsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Counts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Counts
   * const counts = await prisma.counts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends countsUpdateManyArgs>(args: Prisma.SelectSubset<T, countsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Counts and returns the data updated in the database.
   * @param {countsUpdateManyAndReturnArgs} args - Arguments to update many Counts.
   * @example
   * // Update many Counts
   * const counts = await prisma.counts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Counts and only return the `id`
   * const countsWithIdOnly = await prisma.counts.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends countsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, countsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Counts.
   * @param {countsUpsertArgs} args - Arguments to update or create a Counts.
   * @example
   * // Update or create a Counts
   * const counts = await prisma.counts.upsert({
   *   create: {
   *     // ... data to create a Counts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Counts we want to update
   *   }
   * })
   */
  upsert<T extends countsUpsertArgs>(args: Prisma.SelectSubset<T, countsUpsertArgs<ExtArgs>>): Prisma.Prisma__countsClient<runtime.Types.Result.GetResult<Prisma.$countsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Counts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsCountArgs} args - Arguments to filter Counts to count.
   * @example
   * // Count the number of Counts
   * const count = await prisma.counts.count({
   *   where: {
   *     // ... the filter for the Counts we want to count
   *   }
   * })
  **/
  count<T extends countsCountArgs>(
    args?: Prisma.Subset<T, countsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CountsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Counts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CountsAggregateArgs>(args: Prisma.Subset<T, CountsAggregateArgs>): Prisma.PrismaPromise<GetCountsAggregateType<T>>

  /**
   * Group by Counts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {countsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends countsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: countsGroupByArgs['orderBy'] }
      : { orderBy?: countsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, countsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCountsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the counts model
 */
readonly fields: countsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for counts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__countsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  projects<T extends Prisma.projectsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.projectsDefaultArgs<ExtArgs>>): Prisma.Prisma__projectsClient<runtime.Types.Result.GetResult<Prisma.$projectsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the counts model
 */
export interface countsFieldRefs {
  readonly id: Prisma.FieldRef<"counts", 'String'>
  readonly id_project: Prisma.FieldRef<"counts", 'String'>
  readonly logged_on: Prisma.FieldRef<"counts", 'DateTime'>
}
    

// Custom InputTypes
/**
 * counts findUnique
 */
export type countsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter, which counts to fetch.
   */
  where: Prisma.countsWhereUniqueInput
}

/**
 * counts findUniqueOrThrow
 */
export type countsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter, which counts to fetch.
   */
  where: Prisma.countsWhereUniqueInput
}

/**
 * counts findFirst
 */
export type countsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter, which counts to fetch.
   */
  where?: Prisma.countsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of counts to fetch.
   */
  orderBy?: Prisma.countsOrderByWithRelationInput | Prisma.countsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for counts.
   */
  cursor?: Prisma.countsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` counts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` counts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of counts.
   */
  distinct?: Prisma.CountsScalarFieldEnum | Prisma.CountsScalarFieldEnum[]
}

/**
 * counts findFirstOrThrow
 */
export type countsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter, which counts to fetch.
   */
  where?: Prisma.countsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of counts to fetch.
   */
  orderBy?: Prisma.countsOrderByWithRelationInput | Prisma.countsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for counts.
   */
  cursor?: Prisma.countsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` counts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` counts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of counts.
   */
  distinct?: Prisma.CountsScalarFieldEnum | Prisma.CountsScalarFieldEnum[]
}

/**
 * counts findMany
 */
export type countsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter, which counts to fetch.
   */
  where?: Prisma.countsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of counts to fetch.
   */
  orderBy?: Prisma.countsOrderByWithRelationInput | Prisma.countsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing counts.
   */
  cursor?: Prisma.countsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` counts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` counts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of counts.
   */
  distinct?: Prisma.CountsScalarFieldEnum | Prisma.CountsScalarFieldEnum[]
}

/**
 * counts create
 */
export type countsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * The data needed to create a counts.
   */
  data: Prisma.XOR<Prisma.countsCreateInput, Prisma.countsUncheckedCreateInput>
}

/**
 * counts createMany
 */
export type countsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many counts.
   */
  data: Prisma.countsCreateManyInput | Prisma.countsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * counts createManyAndReturn
 */
export type countsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * The data used to create many counts.
   */
  data: Prisma.countsCreateManyInput | Prisma.countsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * counts update
 */
export type countsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * The data needed to update a counts.
   */
  data: Prisma.XOR<Prisma.countsUpdateInput, Prisma.countsUncheckedUpdateInput>
  /**
   * Choose, which counts to update.
   */
  where: Prisma.countsWhereUniqueInput
}

/**
 * counts updateMany
 */
export type countsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update counts.
   */
  data: Prisma.XOR<Prisma.countsUpdateManyMutationInput, Prisma.countsUncheckedUpdateManyInput>
  /**
   * Filter which counts to update
   */
  where?: Prisma.countsWhereInput
  /**
   * Limit how many counts to update.
   */
  limit?: number
}

/**
 * counts updateManyAndReturn
 */
export type countsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * The data used to update counts.
   */
  data: Prisma.XOR<Prisma.countsUpdateManyMutationInput, Prisma.countsUncheckedUpdateManyInput>
  /**
   * Filter which counts to update
   */
  where?: Prisma.countsWhereInput
  /**
   * Limit how many counts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * counts upsert
 */
export type countsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * The filter to search for the counts to update in case it exists.
   */
  where: Prisma.countsWhereUniqueInput
  /**
   * In case the counts found by the `where` argument doesn't exist, create a new counts with this data.
   */
  create: Prisma.XOR<Prisma.countsCreateInput, Prisma.countsUncheckedCreateInput>
  /**
   * In case the counts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.countsUpdateInput, Prisma.countsUncheckedUpdateInput>
}

/**
 * counts delete
 */
export type countsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
  /**
   * Filter which counts to delete.
   */
  where: Prisma.countsWhereUniqueInput
}

/**
 * counts deleteMany
 */
export type countsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which counts to delete
   */
  where?: Prisma.countsWhereInput
  /**
   * Limit how many counts to delete.
   */
  limit?: number
}

/**
 * counts without action
 */
export type countsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the counts
   */
  select?: Prisma.countsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the counts
   */
  omit?: Prisma.countsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.countsInclude<ExtArgs> | null
}
